development:
  database: professionalqa_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: root

test:
  database: professionalqa_test
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: professionalqa
  password:

production:
  database: professionalqa_production
  username: professionalqa
  password: <%= ENV['PROFESSIONALQA_DATABASE_PASSWORD'] %>
